#!/usr/bin/env bash
set -euo pipefail

install_dir=/opt/file-manager-agent
config_dir=/etc/file-manager-agent
listen_host=
port=3091
managed_root=/
display_root=/
hub_url=
enrollment_token=
node_name=
node_id=
download_dir=
source_url=

usage() {
  cat <<'EOF'
Usage: sudo ./deploy/install-agent.sh [options]

Installs a root-level File Manager agent as a systemd service.

Options:
  --listen-host ADDRESS  Private-network address to bind (defaults to Tailscale IPv4)
  --port PORT            Agent port (default: 3091)
  --root PATH            Filesystem subtree to expose (default: /)
  --display-root PATH    Path shown in the UI (default: /)
  --hub-url URL          Hub URL used for automatic enrollment
  --enrollment-token TOKEN
                         Single-use token generated by the hub
  --name NAME            Node label shown in the UI (defaults to hostname)
  --id ID                Stable lowercase node ID (derived from name by default)
  --source-url URL       Agent source bundle (set automatically by the hub)
  -h, --help             Show this help

The installer generates /etc/file-manager-agent/token if it does not exist.
It never prints the token.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --listen-host) listen_host=${2:-}; shift 2 ;;
    --port) port=${2:-}; shift 2 ;;
    --root) managed_root=${2:-}; shift 2 ;;
    --display-root) display_root=${2:-}; shift 2 ;;
    --hub-url) hub_url=${2:-}; shift 2 ;;
    --enrollment-token) enrollment_token=${2:-}; shift 2 ;;
    --name) node_name=${2:-}; shift 2 ;;
    --id) node_id=${2:-}; shift 2 ;;
    --source-url) source_url=${2:-}; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'Unknown option: %s\n' "$1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ ${EUID} -ne 0 ]]; then
  echo 'Run this installer with sudo or as root.' >&2
  exit 1
fi
if [[ -z ${listen_host} ]] && command -v tailscale >/dev/null 2>&1; then
  listen_host=$(tailscale ip -4 2>/dev/null | head -n 1 || true)
fi
if [[ -z ${listen_host} || ${listen_host} == 0.0.0.0 || ${listen_host} == :: ]]; then
  echo 'Unable to detect a Tailscale IPv4 address. Pass --listen-host with a specific private-network address.' >&2
  exit 2
fi
if ! node -e 'process.exit(require("node:net").isIP(process.argv[1]) ? 0 : 1)' "${listen_host}"; then
  echo '--listen-host must be an IPv4 or IPv6 address assigned to this node.' >&2
  exit 2
fi
if [[ ! ${port} =~ ^[0-9]+$ ]] || (( port < 1 || port > 65535 )); then
  echo '--port must be between 1 and 65535.' >&2
  exit 2
fi
if [[ ${managed_root} != /* || ${display_root} != /* ]]; then
  echo '--root and --display-root must be absolute paths.' >&2
  exit 2
fi
if [[ ! -d ${managed_root} ]]; then
  echo "Managed root does not exist: ${managed_root}" >&2
  exit 2
fi
for command in node npm openssl systemctl; do
  if ! command -v "${command}" >/dev/null 2>&1; then
    echo "Missing required command: ${command}" >&2
    exit 1
  fi
done

if [[ -n ${hub_url} || -n ${enrollment_token} ]]; then
  if [[ -z ${hub_url} || -z ${enrollment_token} ]]; then
    echo '--hub-url and --enrollment-token must be provided together.' >&2
    exit 2
  fi
  if ! node -e 'const value = new URL(process.argv[1]); process.exit(["http:", "https:"].includes(value.protocol) && !value.username && !value.password ? 0 : 1)' "${hub_url}"; then
    echo '--hub-url must be an HTTP or HTTPS URL without embedded credentials.' >&2
    exit 2
  fi
fi

node_name=${node_name:-$(hostname)}
if [[ -z ${node_id} ]]; then
  node_id=$(printf '%s' "${node_name}" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//' | cut -c1-63)
fi
if [[ ! ${node_id} =~ ^[a-z0-9][a-z0-9-]{0,62}$ ]]; then
  echo '--id must contain only lowercase letters, digits, and hyphens.' >&2
  exit 2
fi

source_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
if [[ ! -f ${source_dir}/package.json ]]; then
  for command in curl tar; do
    if ! command -v "${command}" >/dev/null 2>&1; then
      echo "Missing required command for remote installation: ${command}" >&2
      exit 1
    fi
  done
  download_dir=$(mktemp -d /tmp/file-manager-source.XXXXXX)
  source_url=${source_url:-https://github.com/purva-labs/file-manager/archive/refs/heads/main.tar.gz}
  curl -fsSL "${source_url}" | tar -xz -C "${download_dir}"
  if [[ ! -f ${download_dir}/package.json ]]; then
    nested_source=$(find "${download_dir}" -mindepth 2 -maxdepth 2 -name package.json -print -quit)
    if [[ -z ${nested_source} ]]; then
      echo 'Downloaded agent source bundle is invalid.' >&2
      exit 1
    fi
    source_dir=$(dirname "${nested_source}")
  else
    source_dir=${download_dir}
  fi
fi
stage_dir=$(mktemp -d "${install_dir}.new.XXXXXX")
cleanup() {
  if [[ -n ${stage_dir:-} && -d ${stage_dir} ]]; then
    find "${stage_dir}" -depth -delete
  fi
  if [[ -n ${download_dir:-} && -d ${download_dir} ]]; then
    find "${download_dir}" -depth -delete
  fi
}
trap cleanup EXIT

install -d -m 0755 "${stage_dir}/src" "${stage_dir}/public"
install -m 0644 "${source_dir}/package.json" "${source_dir}/package-lock.json" "${stage_dir}/"
find "${source_dir}/src" -maxdepth 1 -type f -exec install -m 0644 -t "${stage_dir}/src" {} +
find "${source_dir}/public" -maxdepth 1 -type f -exec install -m 0644 -t "${stage_dir}/public" {} +
npm ci --omit=dev --prefix "${stage_dir}"

install -d -o root -g root -m 0700 "${config_dir}"
if [[ ! -s ${config_dir}/token ]]; then
  umask 077
  openssl rand -hex 32 > "${config_dir}/token"
fi
chown root:root "${config_dir}/token"
chmod 0600 "${config_dir}/token"

env_tmp=$(mktemp)
printf 'PORT=%s\nFILEMANAGER_LISTEN_HOST=%s\nFILEMANAGER_ROOT=%s\nFILEMANAGER_DISPLAY_ROOT=%s\n' \
  "${port}" "${listen_host}" "${managed_root}" "${display_root}" > "${env_tmp}"
install -o root -g root -m 0600 "${env_tmp}" "${config_dir}/agent.env"
rm -f "${env_tmp}"

systemctl stop file-manager-agent.service 2>/dev/null || true
if [[ -d ${install_dir} ]]; then
  previous_dir=${install_dir}.previous
  if [[ -d ${previous_dir} ]]; then
    find "${previous_dir}" -depth -delete
  fi
  mv "${install_dir}" "${previous_dir}"
fi
mv "${stage_dir}" "${install_dir}"
stage_dir=
chown -R root:root "${install_dir}"
install -o root -g root -m 0644 "${source_dir}/deploy/file-manager-agent.service" /etc/systemd/system/file-manager-agent.service
systemctl daemon-reload
systemctl enable --now file-manager-agent.service

echo "File Manager agent is active on ${listen_host}:${port}."
echo "Token file: ${config_dir}/token (root-only; value not displayed)"

if [[ -n ${hub_url} ]]; then
  node - "${hub_url}" "${enrollment_token}" "${node_id}" "${node_name}" "${listen_host}" "${port}" "${config_dir}/token" <<'NODE'
const fs = require('node:fs');

const [hubUrl, enrollmentToken, id, name, listenHost, port, tokenFile] = process.argv.slice(2);
const token = fs.readFileSync(tokenFile, 'utf8').trim();
const agentHost = listenHost.includes(':') ? `[${listenHost}]` : listenHost;

fetch(new URL('/api/enroll', hubUrl), {
  method: 'POST',
  headers: {
    authorization: `Bearer ${enrollmentToken}`,
    'content-type': 'application/json',
  },
  body: JSON.stringify({ id, name, url: `http://${agentHost}:${port}`, token }),
}).then(async (response) => {
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || `Hub returned HTTP ${response.status}`);
  process.stdout.write(`Enrolled ${body.node.name} with the File Manager hub.\n`);
}).catch((error) => {
  process.stderr.write(`Agent is installed, but enrollment failed: ${error.message}\n`);
  process.exitCode = 1;
});
NODE
fi
