#!/usr/bin/env bash
set -euo pipefail

source_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
output_dir=$(realpath -m -- "${1:-${source_dir}/dist/homeassistant-addon}")
marker_file=${output_dir}/.file-manager-homeassistant-bundle

if [[ ${output_dir} == / || ${output_dir} == "${source_dir}" ]]; then
  echo 'Refusing unsafe output directory.' >&2
  exit 2
fi
if [[ -e ${output_dir} ]]; then
  if [[ ! -f ${marker_file} ]]; then
    echo "Refusing to replace an unrecognized directory: ${output_dir}" >&2
    exit 2
  fi
  find "${output_dir}" -depth -delete
fi

install -d -m 0755 "${output_dir}/src" "${output_dir}/public"
printf 'Generated by deploy/package-homeassistant-addon.sh\n' > "${marker_file}"
install -m 0644 \
  "${source_dir}/package.json" \
  "${source_dir}/package-lock.json" \
  "${source_dir}/deploy/homeassistant-addon/config.yaml" \
  "${source_dir}/deploy/homeassistant-addon/Dockerfile" \
  "${output_dir}/"
install -m 0755 "${source_dir}/deploy/homeassistant-addon/run.sh" "${output_dir}/run.sh"
find "${source_dir}/src" -maxdepth 1 -type f -exec install -m 0644 -t "${output_dir}/src" {} +
find "${source_dir}/public" -maxdepth 1 -type f -exec install -m 0644 -t "${output_dir}/public" {} +

echo "Home Assistant app bundle created at ${output_dir}"
